version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  spring-app:
    image: kp/url-shortener:latest
    ports:
      - "9999:9999"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shortener
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_DATABASE: POSTGRESQL
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
