# Def profile configuration

# Data source settings for H2
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:shortenerdb
    username: sa
    password:

  # flyway settings for H2
  flyway:
    url: jdbc:h2:mem:shortener
    user: sa
    password:

  # JPA and Hibernate setup for H2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

# Server port
server:
  port: 9999