# Data source settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

flyway:
  url: jdbc:postgresql://localhost:5432/shortener
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}

# JPA and Hibernate setup
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Server port
server:
  port: 9999